Model and Migration
sadaf-Daneshgar/budget_app pull request #2
Opened 2023-12-22 17:27 UTC by sadaf-Daneshgar

**New Features** 🥇 
-----------------------------
- Added the Migration.
- Added the Model.
- Added the devise.

2024-01-09 18:20 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @sadaf-Daneshgar,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=Typography%3A%20font%20face%2C%20size%20and%20weight.), Please use the correct font family for text elements of the app which is `Proxima nova bold and light`.

![image](https://github.com/sadaf-Daneshgar/budget_app/assets/68796232/3781d99d-a76d-4a51-bd28-857e68547376)

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-01-09 18:20 UTC, omar-muhamad commented on app/views/categories/index.html.erb
> +        </div>
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=size%20and%20weight.-,Layout%3A%20composition%20and%20space%20between%20elements.,-NOTE%3A%20In%20these), Please add a fixed width and height for the category image, because when I add an image link for a medium or big image the layout of the page looks weird.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://github.com/sadaf-Daneshgar/budget_app/assets/68796232/0d055540-a8ea-4a63-afb2-182272365b04) | ![image](https://github.com/sadaf-Daneshgar/budget_app/assets/68796232/c77ed587-70a0-4e46-93ea-b37377fd62b1)  |

2024-01-09 18:20 UTC, omar-muhamad commented on app/views/expenses/index.html.erb
> +  <%= link_to root_path, class: "back-icon" do %></span><% end %>
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=a%20new%20transaction.-,When%20the%20user%20clicks%20on%20the%20%22Back%22%20button%20(%3C)%2C%20the%20user%20navigates%20to%20the%20home%20page.,-%22Add%20a%20new), Please make the app navigate to the categories page (home page) when the back button (the arrow) is clicked, because now the app navigates to the splash screen page.

2024-01-09 18:20 UTC, omar-muhamad commented on app/views/categories/index.html.erb
> + <%= link_to root_path, class: "back-icon" do %></span><% end %>
- [ ] You don't need a back button here because this is the home page of the app and the requirements didn't mention it. Please remove it or better you can replace it with a logout button (logo).

2024-01-09 18:20 UTC, omar-muhamad commented on app/views/categories/new.html.erb
> +  <%= link_to root_path, class: "back-icon" do %></span><% end %>
- [ ] Same here, as per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=page%20on%20success.-,When%20the%20user%20clicks%20on%20the%20%22Back%22%20button%20(%3C)%2C%20the%20user%20navigates%20to%20the%20home%20page.,-%22Add%20a%20new), When the user clicks on the "Back" button (<), the user navigates to the home page(Categories page). Please achieve this requirement because the app now is navigating to the splash screen page.

2024-01-10 06:36 UTC, skyv26 approved these changes
## Hi @sadaf-Daneshgar, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDJhMjgwMDkxOGE3NjA4MjIzYTVjYmExMTFiNmUxYjgxN2FlN2U5NCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PXM/FEzcI0TlDxkdbaHTwV/giphy.gif)

## Highlights
- Implemented the features ✅ 
- Nice *UI* design ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-10 07:38 UTC, sadaf-Daneshgar commented
Hello @skyv26 thanks for your nice review 👍

2024-01-26 08:31 UTC, merged